name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Install ESLint
      run: npm init @eslint/config
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
